version: "3"

services:

  demo:
    image: demo:latest
    networks:
      - my-network
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: mysql
    network:
      - my-network
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=demo
networks:
  my-network:



